/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'Boot.Release+STM32H7S78-DK' 
 * Target:  'Release+STM32H7S78-DK' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32h7rsxx.h"


#endif /* RTE_COMPONENTS_H */
